// Code generated by protoc-gen-go. DO NOT EDIT.
// source: translation.proto

/*
Package translation is a generated protocol buffer package.

It is generated from these files:
	translation.proto

It has these top-level messages:
	Text
	Translation
*/
package translation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Text struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Translation struct {
	Audio []byte `protobuf:"bytes,1,opt,name=Audio,proto3" json:"Audio,omitempty"`
}

func (m *Translation) Reset()                    { *m = Translation{} }
func (m *Translation) String() string            { return proto.CompactTextString(m) }
func (*Translation) ProtoMessage()               {}
func (*Translation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Translation) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func init() {
	proto.RegisterType((*Text)(nil), "translation.Text")
	proto.RegisterType((*Translation)(nil), "translation.Translation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TextToTranslation service

type TextToTranslationClient interface {
	Say(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Translation, error)
}

type textToTranslationClient struct {
	cc *grpc.ClientConn
}

func NewTextToTranslationClient(cc *grpc.ClientConn) TextToTranslationClient {
	return &textToTranslationClient{cc}
}

func (c *textToTranslationClient) Say(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Translation, error) {
	out := new(Translation)
	err := grpc.Invoke(ctx, "/translation.TextToTranslation/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TextToTranslation service

type TextToTranslationServer interface {
	Say(context.Context, *Text) (*Translation, error)
}

func RegisterTextToTranslationServer(s *grpc.Server, srv TextToTranslationServer) {
	s.RegisterService(&_TextToTranslation_serviceDesc, srv)
}

func _TextToTranslation_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToTranslationServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translation.TextToTranslation/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToTranslationServer).Say(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

var _TextToTranslation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "translation.TextToTranslation",
	HandlerType: (*TextToTranslationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _TextToTranslation_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "translation.proto",
}

func init() { proto.RegisterFile("translation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x29, 0x4a, 0xcc,
	0x2b, 0xce, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0x92, 0xe2, 0x62, 0x09, 0x49, 0xad, 0x28, 0x11, 0x12, 0xe2, 0x62, 0x29, 0x49, 0xad,
	0x28, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb9, 0xb8, 0x43, 0x10,
	0x4a, 0x85, 0x44, 0xb8, 0x58, 0x1d, 0x4b, 0x53, 0x32, 0xf3, 0xc1, 0x6a, 0x78, 0x82, 0x20, 0x1c,
	0x23, 0x4f, 0x2e, 0x41, 0x90, 0x01, 0x21, 0xf9, 0xc8, 0x4a, 0x4d, 0xb8, 0x98, 0x83, 0x13, 0x2b,
	0x85, 0x04, 0xf5, 0x90, 0x6d, 0x07, 0x29, 0x93, 0x92, 0x40, 0x15, 0x42, 0x72, 0x09, 0x43, 0x12,
	0x1b, 0xd8, 0x7d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x93, 0x05, 0xf3, 0xb4, 0x00,
	0x00, 0x00,
}
